//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arbitration_Table
    {
        public int ArbitrationID { get; set; }
        public Nullable<System.DateTime> ArbitrationDate { get; set; }
        public Nullable<int> Beneficiaries_ID { get; set; }
        public string FirstSocialstatus { get; set; }
        public string SecondSideName { get; set; }
        public string SecondSideIDNumber { get; set; }
        public string SecondSidePhone { get; set; }
        public string SecondSocialstatus { get; set; }
        public string SecondSideAddress { get; set; }
        public string ArbitrationName { get; set; }
        public string ArbitrationPhone { get; set; }
        public string ArbitrationDecision { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<int> Area_ID { get; set; }
        public Nullable<int> Governorate_ID { get; set; }
    
        public virtual Area_Table Area_Table { get; set; }
        public virtual Beneficiaries_Table Beneficiaries_Table { get; set; }
        public virtual Governorate_Table Governorate_Table { get; set; }
        public virtual Project_Table Project_Table { get; set; }
        public virtual Users_Table Users_Table { get; set; }
    }
}
