//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulting_Table
    {
        public int ConsultingID { get; set; }
        public Nullable<System.DateTime> ConsultingDate { get; set; }
        public string ConsultantName { get; set; }
        public string Gender { get; set; }
        public Nullable<int> Age { get; set; }
        public string CounselingRequired { get; set; }
        public string CounselingRendered { get; set; }
        public Nullable<int> LawyerID { get; set; }
        public string CounselingStatus { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> TypeOfCaseID { get; set; }
        public Nullable<int> IssuesTypeID { get; set; }
        public Nullable<int> ProjectID { get; set; }
    
        public virtual IssuesType_Table IssuesType_Table { get; set; }
        public virtual Lawyer_Table Lawyer_Table { get; set; }
        public virtual Project_Table Project_Table { get; set; }
        public virtual TypeOfCase_Table TypeOfCase_Table { get; set; }
        public virtual Users_Table Users_Table { get; set; }
    }
}
