//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiligenceType_Table
    {
        public DiligenceType_Table()
        {
            this.Mediation_Table = new HashSet<Mediation_Table>();
        }
    
        public int DiligenceTypeID { get; set; }
        public string DiligenceTypeName { get; set; }
    
        public virtual ICollection<Mediation_Table> Mediation_Table { get; set; }
    }
}
