//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FamilyWatch_Table
    {
        public int FamilyWatchID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> timeFrom { get; set; }
        public Nullable<System.DateTime> TimeTo { get; set; }
        public string Attendees { get; set; }
        public Nullable<System.DateTime> HoursAttendance { get; set; }
        public Nullable<System.DateTime> hourDeparture { get; set; }
        public string Specialist { get; set; }
        public string Notes { get; set; }
        public Nullable<int> FamilyForumID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CustodialAttendees { get; set; }
        public Nullable<System.DateTime> CustodialHoursAttendance { get; set; }
        public Nullable<System.DateTime> CustodialhourDeparture { get; set; }
    
        public virtual FamilyForum_Table FamilyForum_Table { get; set; }
        public virtual Users_Table Users_Table { get; set; }
    }
}
