//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gender_Table
    {
        public Gender_Table()
        {
            this.Beneficiaries_Table = new HashSet<Beneficiaries_Table>();
        }
    
        public int GenderID { get; set; }
        public string GenderName { get; set; }
    
        public virtual ICollection<Beneficiaries_Table> Beneficiaries_Table { get; set; }
    }
}
