//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuesType_Table
    {
        public IssuesType_Table()
        {
            this.Consulting_Table = new HashSet<Consulting_Table>();
            this.Courts_Table = new HashSet<Courts_Table>();
            this.Legal_Assistance_Table = new HashSet<Legal_Assistance_Table>();
            this.Mediation_Table = new HashSet<Mediation_Table>();
            this.Order_Table = new HashSet<Order_Table>();
            this.TypeOfCase_Table = new HashSet<TypeOfCase_Table>();
        }
    
        public int IssuesTypeID { get; set; }
        public string IssuesTypename { get; set; }
    
        public virtual ICollection<Consulting_Table> Consulting_Table { get; set; }
        public virtual ICollection<Courts_Table> Courts_Table { get; set; }
        public virtual ICollection<Legal_Assistance_Table> Legal_Assistance_Table { get; set; }
        public virtual ICollection<Mediation_Table> Mediation_Table { get; set; }
        public virtual ICollection<Order_Table> Order_Table { get; set; }
        public virtual ICollection<TypeOfCase_Table> TypeOfCase_Table { get; set; }
    }
}
