//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IssuesStatus_Table
    {
        public IssuesStatus_Table()
        {
            this.LegalIssues_Table = new HashSet<LegalIssues_Table>();
            this.SystemicIssues_Table = new HashSet<SystemicIssues_Table>();
        }
    
        public int IssuesStatusID { get; set; }
        public string IssuesStatusName { get; set; }
    
        public virtual ICollection<LegalIssues_Table> LegalIssues_Table { get; set; }
        public virtual ICollection<SystemicIssues_Table> SystemicIssues_Table { get; set; }
    }
}
