//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaType_Table
    {
        public MediaType_Table()
        {
            this.Media_Table = new HashSet<Media_Table>();
        }
    
        public int MediaTypeID { get; set; }
        public string MediaTypeName { get; set; }
    
        public virtual ICollection<Media_Table> Media_Table { get; set; }
    }
}
