//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Table
    {
        public Project_Table()
        {
            this.Achievements_Table = new HashSet<Achievements_Table>();
            this.Advocacyactivities_Table = new HashSet<Advocacyactivities_Table>();
            this.Arbitration_Table = new HashSet<Arbitration_Table>();
            this.AwarenessWorkshops_Table = new HashSet<AwarenessWorkshops_Table>();
            this.Consulting_Table = new HashSet<Consulting_Table>();
            this.Courses_Table = new HashSet<Courses_Table>();
            this.FamilyForum_Table = new HashSet<FamilyForum_Table>();
            this.Media_Table = new HashSet<Media_Table>();
            this.Mediation_Table = new HashSet<Mediation_Table>();
            this.ProjectControl_Table = new HashSet<ProjectControl_Table>();
            this.SystemicIssues_Table = new HashSet<SystemicIssues_Table>();
            this.Versions_Table = new HashSet<Versions_Table>();
        }
    
        public int ProjectID { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.DateTime> StartData { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual ICollection<Achievements_Table> Achievements_Table { get; set; }
        public virtual ICollection<Advocacyactivities_Table> Advocacyactivities_Table { get; set; }
        public virtual ICollection<Arbitration_Table> Arbitration_Table { get; set; }
        public virtual ICollection<AwarenessWorkshops_Table> AwarenessWorkshops_Table { get; set; }
        public virtual ICollection<Consulting_Table> Consulting_Table { get; set; }
        public virtual ICollection<Courses_Table> Courses_Table { get; set; }
        public virtual ICollection<FamilyForum_Table> FamilyForum_Table { get; set; }
        public virtual ICollection<Media_Table> Media_Table { get; set; }
        public virtual ICollection<Mediation_Table> Mediation_Table { get; set; }
        public virtual ICollection<ProjectControl_Table> ProjectControl_Table { get; set; }
        public virtual ICollection<SystemicIssues_Table> SystemicIssues_Table { get; set; }
        public virtual ICollection<Versions_Table> Versions_Table { get; set; }
    }
}
