//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetGroup_Table
    {
        public TargetGroup_Table()
        {
            this.Courses_Table = new HashSet<Courses_Table>();
        }
    
        public int TargetGroupID { get; set; }
        public string TargetGroupName { get; set; }
    
        public virtual ICollection<Courses_Table> Courses_Table { get; set; }
    }
}
