//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Courses_Table
    {
        public Courses_Table()
        {
            this.Trainees_Table = new HashSet<Trainees_Table>();
        }
    
        public int CoursesID { get; set; }
        public string CoursesNumber { get; set; }
        public Nullable<System.DateTime> CoursesStartDate { get; set; }
        public Nullable<System.DateTime> CoursesEndDate { get; set; }
        public string CoursesSummary { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Users_Table Users_Table { get; set; }
        public virtual ICollection<Trainees_Table> Trainees_Table { get; set; }
    }
}
