//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LawyersEntities : DbContext
    {
        public LawyersEntities()
            : base("name=LawyersEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Achievements_Table> Achievements_Table { get; set; }
        public DbSet<Arbitration_Table> Arbitration_Table { get; set; }
        public DbSet<Consulting_Table> Consulting_Table { get; set; }
        public DbSet<Courses_Table> Courses_Table { get; set; }
        public DbSet<Courts_Table> Courts_Table { get; set; }
        public DbSet<FamilyForum_Table> FamilyForum_Table { get; set; }
        public DbSet<Lawyer_Table> Lawyer_Table { get; set; }
        public DbSet<LegalIssues_Table> LegalIssues_Table { get; set; }
        public DbSet<LegalSession_Table> LegalSession_Table { get; set; }
        public DbSet<Mediation_Table> Mediation_Table { get; set; }
        public DbSet<SystemicIssues_Table> SystemicIssues_Table { get; set; }
        public DbSet<SystemicOrder_Table> SystemicOrder_Table { get; set; }
        public DbSet<SystemicSession_Table> SystemicSession_Table { get; set; }
        public DbSet<Trainees_Table> Trainees_Table { get; set; }
        public DbSet<TypeOfCase_Table> TypeOfCase_Table { get; set; }
        public DbSet<Users_Table> Users_Table { get; set; }
    }
}
