//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemicIssues_Table
    {
        public SystemicIssues_Table()
        {
            this.SystemicOrder_Table = new HashSet<SystemicOrder_Table>();
            this.SystemicSession_Table = new HashSet<SystemicSession_Table>();
        }
    
        public int SystemicIssuesID { get; set; }
        public string CenterNumber { get; set; }
        public string CourtsNumber { get; set; }
        public Nullable<System.DateTime> DateOfCase { get; set; }
        public Nullable<System.DateTime> DepositDate { get; set; }
        public string ClientName { get; set; }
        public string ClientIDNumber { get; set; }
        public string ClientPhone { get; set; }
        public string ClientAddress { get; set; }
        public string AdversaryName { get; set; }
        public string AdversaryIDNumber { get; set; }
        public string AdversaryPhone { get; set; }
        public string AdversaryAddress { get; set; }
        public Nullable<int> TypeOfCaseID { get; set; }
        public Nullable<int> CourtsID { get; set; }
        public Nullable<int> LawyerID { get; set; }
        public Nullable<System.DateTime> DateOfClosure { get; set; }
        public Nullable<int> UserID { get; set; }
    
        public virtual Courts_Table Courts_Table { get; set; }
        public virtual Lawyer_Table Lawyer_Table { get; set; }
        public virtual TypeOfCase_Table TypeOfCase_Table { get; set; }
        public virtual Users_Table Users_Table { get; set; }
        public virtual ICollection<SystemicOrder_Table> SystemicOrder_Table { get; set; }
        public virtual ICollection<SystemicSession_Table> SystemicSession_Table { get; set; }
    }
}
