//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trainees_Table
    {
        public int TraineesID { get; set; }
        public string TraineesName { get; set; }
        public string TraineesPhone { get; set; }
        public string TraineesSpecialty { get; set; }
        public Nullable<int> CoursesID { get; set; }
    
        public virtual Courses_Table Courses_Table { get; set; }
    }
}
