//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LawyersApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users_Table
    {
        public Users_Table()
        {
            this.Achievements_Table = new HashSet<Achievements_Table>();
            this.Arbitration_Table = new HashSet<Arbitration_Table>();
            this.Consulting_Table = new HashSet<Consulting_Table>();
            this.Courses_Table = new HashSet<Courses_Table>();
            this.FamilyForum_Table = new HashSet<FamilyForum_Table>();
            this.LegalIssues_Table = new HashSet<LegalIssues_Table>();
            this.LegalSession_Table = new HashSet<LegalSession_Table>();
            this.Mediation_Table = new HashSet<Mediation_Table>();
            this.SystemicIssues_Table = new HashSet<SystemicIssues_Table>();
            this.SystemicOrder_Table = new HashSet<SystemicOrder_Table>();
            this.SystemicSession_Table = new HashSet<SystemicSession_Table>();
        }
    
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserType { get; set; }
        public bool Status { get; set; }
    
        public virtual ICollection<Achievements_Table> Achievements_Table { get; set; }
        public virtual ICollection<Arbitration_Table> Arbitration_Table { get; set; }
        public virtual ICollection<Consulting_Table> Consulting_Table { get; set; }
        public virtual ICollection<Courses_Table> Courses_Table { get; set; }
        public virtual ICollection<FamilyForum_Table> FamilyForum_Table { get; set; }
        public virtual ICollection<LegalIssues_Table> LegalIssues_Table { get; set; }
        public virtual ICollection<LegalSession_Table> LegalSession_Table { get; set; }
        public virtual ICollection<Mediation_Table> Mediation_Table { get; set; }
        public virtual ICollection<SystemicIssues_Table> SystemicIssues_Table { get; set; }
        public virtual ICollection<SystemicOrder_Table> SystemicOrder_Table { get; set; }
        public virtual ICollection<SystemicSession_Table> SystemicSession_Table { get; set; }
    }
}
